name: Create each PlatformIO EleksTubeHAX environment build on multiple OSes.

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write # Required to list/delete caches during pruning

env:
  PIO_DIR: EleksTubeHAX_pio # Set project base dir once here
  GH_TOKEN: ${{ github.token }}
  GITHUB_TOKEN: ${{ github.token }}
  CI: true
  GH_PROMPT_DISABLED: "1"
  GH_PAGER: cat
  GH_NO_UPDATE_NOTIFIER: "1"

jobs:
  discover-envs:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.find.outputs.envs }}
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Find [env:*] sections in platformio.ini file.
        id: find
        shell: bash
        working-directory: ${{ env.PIO_DIR }}
        run: |
          envs_json="$(
            awk '
              /^\[env:[^]]+\]/ {
                match($0, /^\[env:([^]]+)\]/, m)
                if (m[1] != "") envs[count++] = m[1]
              }
              END {
                printf("[")
                for (i=0; i<count; i++) printf("%s\"%s\"", (i>0?",":""), envs[i])
                printf("]")
              }
            ' platformio.ini
          )"
          echo "envs=${envs_json}" >> "$GITHUB_OUTPUT"
          echo "  🐞 Detected PIO environments: ${envs_json}."

  build:
    name: Build on ${{ matrix.os }}, env=${{ matrix.env }}.
    runs-on: ${{ matrix.os }}
    needs: discover-envs

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 2 configurations:
      # 1. <Windows, Release, toolchain on the default runner image, default generator>
      # 2. <Linux, Release, toolchain on the default runner image, default generator>

      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:        
        os: [ubuntu-latest, windows-latest]
        env: ${{ fromJson(needs.discover-envs.outputs.envs) }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PIO_DIR }}

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      # --- Cache pruning (keep only latest N ~/.platformio caches). ---------
      - name: Install GitHub CLI & jq.
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Prune old PlatformIO caches (gh api; non-interactive, guarded).
        # Only run on branches in this repo (not PRs from forks with read-only token).
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          KEY_PREFIX: ${{ runner.os }}-platformio-
          KEEP: "3" # Adjust as needed
        run: |
          set -euo pipefail

          # If no token is available (e.g., running under `act` without providing one), skip pruning to avoid gh prompts.
          if [ -z "${GH_TOKEN:-${GITHUB_TOKEN:-}}" ]; then
            echo "  ⚠️ GH_TOKEN/GITHUB_TOKEN not set — skipping cache prune to avoid prompts."
            exit 0
          fi

          repo="${{ github.repository }}"
          echo "  🔧 Pruning caches with prefix: ${KEY_PREFIX} (keeping latest ${KEEP})."

          # List all cache pages, filter by prefix, sort by last access desc, drop the newest KEEP, delete the rest.
          gh api --paginate -H "Accept: application/vnd.github+json" \
            "/repos/${repo}/actions/caches?per_page=100" \
          | jq -r --arg p "$KEY_PREFIX" --argjson k "$KEEP" '
              .actions_caches? // empty
              | map(select(.key | startswith($p)))
              | sort_by(.last_accessed_at) | reverse
              | .[$k:] | .[].id
            ' \
          | while read -r id; do
              [ -z "$id" ] && continue
              echo "  🔧 Deleting cache id '$id'."
              gh api --method DELETE "/repos/${repo}/actions/caches/$id" || true
            done
      # ----------------------------------------------------------------------

      - name: Cache PlatformIO core (platforms/frameworks).
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles(format('{0}/platformio.ini', env.PIO_DIR)) }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO + IntelHex and esptool libraries.
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio intelhex esptool

      - name: Ensure default _USER_DEFINES.h file exists.
        shell: bash
        working-directory: ${{ env.PIO_DIR }}
        run: |
          set -euo pipefail
          SRC="include/_USER_DEFINES - empty.h"
          DST="include/_USER_DEFINES.h"
          mkdir -p "$(dirname "$DST")"
          if [[ ! -f "$DST" ]]; then
            if [[ ! -f "$SRC" ]]; then
              echo "  ❌ Source file not found: '$SRC'."
              exit 1
            fi
            cp "$SRC" "$DST"
            echo "  🔧 Copied: '$SRC' -> '$DST'."
          else
            echo "  ⚠️ Already present: '$DST'."
          fi

      - name: Force CREATE_FIRMWAREFILE define in platformio.ini file.
        run: |
          if grep -qE '^\s*;\s*-D\s*CREATE_FIRMWAREFILE' platformio.ini; then
            sed -i 's/^\s*;\s*-D\s*CREATE_FIRMWAREFILE/	-D CREATE_FIRMWAREFILE/' platformio.ini
          fi
          if ! grep -qE '^\s*-D\s*CREATE_FIRMWAREFILE' platformio.ini; then
            awk '
              BEGIN{added=0}
              {print}
              /^\s*build_flags\s*=\s*$/ {print "  -D CREATE_FIRMWAREFILE"; added=1}
              END{ if (!added) print "\nbuild_flags =\n  -D CREATE_FIRMWAREFILE" }
            ' platformio.ini > platformio.ini.new && mv platformio.ini.new platformio.ini
          fi
          echo "  🔧 CREATE_FIRMWAREFILE set."

      - name: Build ${{ matrix.env }} environment.
        run: pio run --environment "${{ matrix.env }}"
